// <auto-generated />
namespace LibraryProject_.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class addValidation : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addValidation));
        
        string IMigrationMetadata.Id
        {
            get { return "202105280304464_addValidation"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
